services:
  postgres:
    image: postgres:16
    container_name: casn_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cn
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d